export const MOVIES_LOADED = "MOVIES_LOADED";
export const ERROR_OCCURRED = "ERROR_OCCURED";
export const VIEWED_MOVIE = "VIEWED_MOVIE";
export const NOT_VIEWED_MOVIE = "NOT_VIEWED_MOVIE";
export const UPDATE_LOADING = "UPDATE_LOADING";
