export const UPDATE_CATALOG = 'UPDATE_CATALOG';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_BRANDS = 'UPDATE_BRANDS';
export const UPDATE_RANGES = 'UPDATE_RANGES';
export const UPDATE_COLORS = 'UPDATE_COLORS';
export const UPDATE_CART = 'UPDATE_CART';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
